config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'accounts#show', as: 'root'
  namespace :accounts do
    resources :transactions, only: %i[new create] do
      get :sent, on: :collection
      get :received, on: :collection    
    end
  end

  get '*path', to: 'accounts#unknown'
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user

  has_many :transactions, :class_name => 'Transaction', :foreign_key => 'sender_id'
  has_many :received_transactions, :class_name => 'Transaction', :foreign_key => 'receiver_id'

  validates :user_id, presence: true, uniqueness: true
  validates :account_number, presence: true, uniqueness:  { case_sensitive: true }
  validates :balance, presence: true, numericality: { greater_than_or_equal_to: 0 }  

  def debit_account(amount)
    new_balance = balance - BigDecimal(amount)
    update balance: new_balance
  end

  def credit_account(amount)
    new_balance = balance + BigDecimal(amount)
    update balance: new_balance    
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :sender, class_name: 'Account'
  belongs_to :receiver, class_name: 'Account'

  validates :sender_id, presence: true
  validates :receiver_id, presence: true
  validates :transaction_uuid, presence: true, uniqueness: {case_sensitive: true}
  validates :amount, presence: true, numericality: { greater_than: 0 }

  validates_with SendingToSelfValidator
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable
  has_one :account, dependent: :destroy
end

app/controllers/accounts/transactions_controller.rb
class Accounts::TransactionsController < ApplicationController
  before_action :authenticate_user!

  def new
    @transaction = @account.transactions.build
  end

  def create
    return amount_not_valid unless amount_valid
    return sending_negative_amount if amount_negative
    return receiver_not_found unless payment_receiver.present?
    return insufficient_balance unless sufficient_balance.present?
    return sending_to_self if sender_same_as_receiver

    PaymentBuilder.new(payment_params).create
    flash[:notice] = 'Transaction successful'
    redirect_to root_path
  rescue ActiveRecord::RecordInvalid
    render action: 'new'
  end

  def sent
    @sent_transactions = @account.transactions.order("created_at DESC")
                                 .paginate(page: params[:page], per_page: 5)   
  end

  def received
    @received_transactions = @account.received_transactions.order("created_at DESC")
                                     .paginate(page: params[:page], per_page: 5)
  end

  private

  def amount_not_valid
    flash[:alert] = "Amount is not  a valid number"
    redirect_to new_accounts_transaction_path 
  end

  def receiver_not_found
    flash[:alert] = "Receiver account not found"
    redirect_to new_accounts_transaction_path    
  end

  def insufficient_balance
    flash[:alert] = "Insufficient funds"
    redirect_to new_accounts_transaction_path
  end

  def sending_to_self
    flash[:alert] = "Can not send to yourself"
    redirect_to new_accounts_transaction_path
  end  

  def sending_negative_amount
    flash[:alert] = "Amount can not be negative"
    redirect_to new_accounts_transaction_path    
  end

  def amount_valid
    BigDecimal(transaction_params[:transaction][:amount], exception: false).present?
  end

  def sender_same_as_receiver
    @account == payment_receiver
  end

  def sufficient_balance
    @account.balance >= BigDecimal(transaction_params[:transaction][:amount])
  end

  def payment_receiver
    @receiver ||= Account.find_by(
      account_number: transaction_params[:account_number]
    )
  end

  def amount_negative
    transaction_params[:transaction][:amount].to_d.negative?
  end

  def payment_params
    {
      amount: transaction_params[:transaction][:amount],
      receiver_id: payment_receiver.id,
      sender_id: @account.id
    }
  end

  def transaction_params
    params.permit(:account_number, transaction: [:amount])
  end  
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
	before_action :authenticate_user!

	def unknown
		flash.notice = 'No page found at that address'
		redirect_to root_path
	end

	def show
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :set_cache_headers ,:set_current_account!
	layout :choose_layout

  def set_current_account!
    return unless user_signed_in?
    logger.debug { 'set_current_account!' }
    @account ||= current_user.account
  end  

  private

  def set_cache_headers
    response.headers["Cache-Control"] = "no-cache, no-store"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "Mon, 01 Jan 1990 00:00:00 GMT"
  end  

	def choose_layout
    user_signed_in? ? 'dashboard' :  'application'
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/show.haml
.container
	.card
		.card-header
			Your account details
		.card-body
			%p.card-text
				= "Account Number: #{@account.account_number}"
			%p.card-text
				= "Account Balance: #{@account.balance}€"

app/views/accounts/transactions/new.haml
.row.mt-4
  .col-lg-6.offset-lg-3
    = bootstrap_form_for @transaction, url: accounts_transactions_path do |f|
      %fieldset
        %legend New Transaction
        .mb-3
          %label.form-label{ for: 'account_number' }
            Recepient Account Number
          %input.form-control#account-number{ name: 'account_number',
                                             value: params[:account_number],
                                             required: true }                 
        = f.text_field :amount, required: true, label_class: 'required'

      %p.text-center
        = f.submit 'Send money', class: 'btn btn-success'
    .container
    = "Current Balance: #{@account.balance}€"

app/views/accounts/transactions/received.haml
%table.table.table-striped
  %tr
    %th.span1 Sender Account
    %th.span1 Sender Name
    %th.span1 Amount
    %th.span1 Date
  - @received_transactions.each do |tr|
    %tr
      %td= tr.sender.account_number
      %td= tr.sender.user.name
      %td= tr.amount
      %td= tr.created_at.strftime('%m/%d/%Y %I:%M %p')

= will_paginate @received_transactions      

app/views/accounts/transactions/sent.haml
%table.table.table-striped
  %tr
    %th.span1 Receiver Account
    %th.span1 Receiver Name
    %th.span1 Amount
    %th.span1 Date
  - @sent_transactions.each do |tr|
    %tr
      %td= tr.receiver.account_number
      %td= tr.receiver.user.name
      %td= tr.amount
      %td= tr.created_at.strftime('%m/%d/%Y %I:%M %p')

= will_paginate @sent_transactions      

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark.navbar-light.bg-light.mt-1
  %a.navbar-brand.px-2{ href: root_path }
    TheDigiBank
  %button.navbar-toggler{ 'aria-controls' => 'navbarSupportedContent', 'aria-expanded' => 'false', 'aria-label' => 'Toggle navigation', 'data-target' => '#navbar-nav-dropdown', 'data-toggle' => 'collapse', :type => 'button' }
  .collapse.navbar-collapse.justify-content-between#navbar-nav-dropdown
    %ul.nav.navbar-nav
      %li.nav-item
        = link_to 'Dashboard', root_path, class: 'nav-link'
      %li.nav-item
        = link_to 'New Transaction', new_accounts_transaction_path, class: 'nav-link'
      %li.nav-item
        = link_to 'Money Sent', sent_accounts_transactions_path, class: 'nav-link'
      %li.nav-item
        = link_to 'Money Received', received_accounts_transactions_path, class: 'nav-link'        
    %ul.nav.navbar-nav.navbar-right
      %li.nav-item
        = link_to "Hi, #{current_user.name}", root_path, class: 'nav-link'
      %li.nav-item.px-2
        = button_to('Log out', destroy_user_session_path, method: :delete,
          type: 'button', class: 'btn btn-danger')

app/views/layouts/application.haml
!!! 5
%html
  %head
    %title= 'Thedigibank'

    = csrf_meta_tag
    = csp_meta_tag
    = stylesheet_link_tag 'application'
    = javascript_pack_tag 'application'

  %body
    .container
      %p.notice
        = notice
      %p.alert
        = alert
      = yield

app/views/layouts/dashboard.haml
!!! 5
%html
  %head
    %title= 'Thedigibank'

    = csrf_meta_tag
    = csp_meta_tag
    = stylesheet_link_tag 'application'
    = javascript_pack_tag 'application'

  %body.app
    .container
      = render partial: '/layouts/header'
      %p.notice
        = notice
      %p.alert
        = alert                
      = yield